// src/components/calculator/Calculator.tsx
import { useMemo, useState } from "react";
import { calculate, preCheck } from "simple-calculate";

const replaceTextList = [
  ["x", "*"],
  ["÷", "/"],
  ["（", "("],
  ["）", ")"],
  [" ", ""],
];

export default function Calculator() {
  const [value, setValue] = useState<string>();

  const result = useMemo(() => {
    let _inputValue = value;
    if (!_inputValue) {
      return;
    }

    // 替换特殊字符
    _inputValue = replaceTextList.reduce<string>((_str, [searchValue, replaceValue]) => {
      return _str.replaceAll(searchValue, replaceValue);
    }, _inputValue);

    if (!preCheck(_inputValue)) {
      return "请勿输入特殊字符";
    }

    try {
      return calculate(_inputValue);
    } catch (error) {
      console.error(error);
      return "";
    }
  }, [value]);

  return (
    <div className="pt-8">
      <input
        value={value}
        onChange={(e) => setValue(e.target.value)}
        className="w-full text-3xl"
        placeholder="输入算式"
      />

      <hr />

      <span>结果: {result}</span>
    </div>
  );
}

// docs/components/calculator/Calculator.vue
<script setup lang="ts">
import { calculate, preCheck } from 'simple-calculate'
import { ref, watch } from 'vue'

const input = defineModel<string>()
const result = ref()
const replaceTextList = [
  ['x', '*'],
  ['÷', '/'],
  ['（', '('],
  ['）', ')'],
  [' ', ''],
]

watch(input, () => {
  // 替换特殊字符
  let _inputValue = input.value

  if (!_inputValue) {
    result.value = ''
    return
  }

  _inputValue = replaceTextList.reduce<string>((_str, [searchValue, replaceValue]) => {
    return _str.replaceAll(searchValue, replaceValue)
  }, _inputValue)

  if (!preCheck(_inputValue)) {
    result.value = '请勿输入特殊字符'
    return
  }

  try {
    result.value = calculate(_inputValue)
  }
  catch (error) {
    result.value = ''
    console.error(error)
  }
})
</script>

<template>
  <div class="pt-8">
    <input
      v-model="input"
      class="w-full text-3xl"
      placeholder="输入算式"
    >

    <hr>

    <span>结果: {{ result }}</span>
  </div>
</template>
